// Embeds rules/rules.bundled.json into the app as a Dart string, so the
// built-in rules can be read synchronously with no asset loading.
//
//   dart run tool/gen_bundled_rules.dart
//
// Edit the JSON, run this, commit both files. A test fails if they drift.
import 'dart:convert';
import 'dart:io';

void main() {
  final json = File('rules/rules.bundled.json').readAsStringSync();
  // Make sure it is valid JSON before baking it in.
  jsonDecode(json);
  if (json.contains("'''")) {
    stderr.writeln("rules.bundled.json must not contain three single quotes in a row");
    exit(1);
  }
  File('lib/core/rules/bundled_rules.g.dart').writeAsStringSync(
    "// GENERATED by tool/gen_bundled_rules.dart from rules/rules.bundled.json — do not edit.\n"
    "// ignore_for_file: lines_longer_than_80_chars\n\n"
    "/// The rules built into this version of the app.\n"
    "const kBundledRulesJson = r'''$json''';\n",
  );
  stdout.writeln('wrote lib/core/rules/bundled_rules.g.dart (${json.length} chars)');
}
