import 'package:flutter/widgets.dart';
import 'package:simple_icons/simple_icons.dart';

/// Logo glyphs a brand rule can name (`"icon": "swiggy"` in the rules JSON).
/// Icons must be referenced as constants so the build can keep only the glyphs
/// used; adding a brand with a new glyph means adding a line here.
const brandIcons = <String, IconData>{
  'adidas': SimpleIcons.adidas,
  'airbnb': SimpleIcons.airbnb,
  'airindia': SimpleIcons.airindia,
  'airtel': SimpleIcons.airtel,
  'americanexpress': SimpleIcons.americanexpress,
  'apple': SimpleIcons.apple,
  'applemusic': SimpleIcons.applemusic,
  'axisbank': SimpleIcons.axisbank,
  'bigbasket': SimpleIcons.bigbasket,
  'bookmyshow': SimpleIcons.bookmyshow,
  'burgerking': SimpleIcons.burgerking,
  'dunzo': SimpleIcons.dunzo,
  'googlepay': SimpleIcons.googlepay,
  'googleplay': SimpleIcons.googleplay,
  'hdfcbank': SimpleIcons.hdfcbank,
  'hsbc': SimpleIcons.hsbc,
  'icicibank': SimpleIcons.icicibank,
  'ikea': SimpleIcons.ikea,
  'indigo': SimpleIcons.indigo,
  'jio': SimpleIcons.jio,
  'kfc': SimpleIcons.kfc,
  'mastercard': SimpleIcons.mastercard,
  'mcdonalds': SimpleIcons.mcdonalds,
  'netflix': SimpleIcons.netflix,
  'nike': SimpleIcons.nike,
  'oyo': SimpleIcons.oyo,
  'paypal': SimpleIcons.paypal,
  'paytm': SimpleIcons.paytm,
  'phonepe': SimpleIcons.phonepe,
  'puma': SimpleIcons.puma,
  'razorpay': SimpleIcons.razorpay,
  'spotify': SimpleIcons.spotify,
  'starbucks': SimpleIcons.starbucks,
  'swiggy': SimpleIcons.swiggy,
  'uber': SimpleIcons.uber,
  'visa': SimpleIcons.visa,
  'vodafone': SimpleIcons.vodafone,
  'youtube': SimpleIcons.youtube,
  'youtubemusic': SimpleIcons.youtubemusic,
  'zerodha': SimpleIcons.zerodha,
  'zomato': SimpleIcons.zomato,
};
